export const caseStudies = [
  {
    id: 1,
    featured: true,
    spotlight: true,
    clientType: "Telecommunications Provider",
    industry: "Telecommunications",
    challenge: "Engineers were spending hours manually searching and matching catalogues for telecom equipment, causing project delays and inconsistent documentation",
    solution: "Built an AI-powered catalogue automation system that intelligently matches items, auto-attaches relevant catalogues, and organizes documentation as per project requirements",
    impact: "Reduced catalogue processing time from hours to minutes, freeing up engineering resources for higher-value work",
    metrics: {
      primary: "90%",
      primaryLabel: "Time saved on catalogue matching",
      secondary: "100%",
      secondaryLabel: "Documentation accuracy",
    },
    technologies: ["AI/ML", "Natural Language Processing", "Document Automation", "Cloud Platform"],
    services: ["AI Engineering", "Process Automation", "Enterprise Software"],
    image: "/images/cloudEngineering/cloud-engineering.jpg",
    slug: "telecom-catalogue-automation",
    excerpt: "AI-powered automation transformed telecom catalogue management with intelligent matching",
  },
  {
    id: 2,
    featured: true,
    spotlight: true,
    clientType: "EV Infrastructure Company",
    industry: "Transport",
    challenge: "Fragmented EV charging station operations with no unified view of fleet status, charging schedules, and energy consumption across multiple locations",
    solution: "Developed a comprehensive EV charging and fleet management platform with real-time monitoring, smart scheduling, and energy optimization",
    impact: "Unified fleet operations with real-time visibility and optimized charging schedules",
    metrics: {
      primary: "40%",
      primaryLabel: "Reduction in energy costs",
      secondary: "Real-time",
      secondaryLabel: "Fleet visibility achieved",
    },
    technologies: ["IoT", "Real-time Analytics", "Mobile Platform", "Cloud Infrastructure"],
    services: ["Product Engineering", "Cloud Engineering", "Integration Engineering"],
    image: "/images/dataEngineering/data-engineering.jpg",
    slug: "ev-fleet-management",
    excerpt: "Unified fleet management platform with smart energy optimization for EV charging operations",
  },
  {
    id: 3,
    featured: true,
    spotlight: true,
    clientType: "Delivery Services Provider",
    industry: "Financial Services",
    challenge: "Disconnected loyalty programs and payment systems causing customer friction, low retention, and missed engagement opportunities",
    solution: "Created an integrated loyalty and payment application combining rewards tracking, seamless payments, and personalized offers in a single mobile experience",
    impact: "Increased customer retention and engagement through unified loyalty rewards and frictionless payment processing",
    metrics: {
      primary: "35%",
      primaryLabel: "Increase in customer retention",
      secondary: "2x",
      secondaryLabel: "Loyalty program engagement",
    },
    technologies: ["Mobile Development", "Payment Gateway", "Real-time Analytics", "API Integration"],
    services: ["Fintech Engineering", "Product Engineering", "Integration Engineering"],
    image: "/images/fintechEngineering/Fintech-engineering.png",
    slug: "loyalty-payment-platform",
    excerpt: "Unified loyalty and payment platform that drives customer engagement and retention",
  },
  {
    id: 4,
    featured: true,
    spotlight: false,
    clientType: "Large Family Community",
    industry: "Community",
    challenge: "Extended family members across generations and geographies losing connection, struggling to trace relationships, and lacking a central platform for news, events, and collective initiatives",
    solution: "Built a comprehensive family community app with relationship mapping, family tree visualization, news feeds, event management, and collective fundraising capabilities",
    impact: "Connected thousands of family members with easy relationship discovery and centralized community engagement",
    metrics: {
      primary: "5000+",
      primaryLabel: "Family members connected",
      secondary: "100%",
      secondaryLabel: "Relationship traceability",
    },
    technologies: ["Mobile Platform", "Graph Database", "Real-time Messaging", "Cloud Infrastructure"],
    services: ["Product Engineering", "Cloud Engineering", "Design Engineering"],
    image: "/images/designEngineering/design-engineering.jpg",
    slug: "family-community-platform",
    excerpt: "Digital platform connecting generations and enabling collective family action",
  },
  {
    id: 5,
    featured: false,
    spotlight: false,
    clientType: "European Training Organization",
    industry: "Education",
    challenge: "Generic LMS platforms failed to accommodate unique business processes, certification requirements, and custom training workflows",
    solution: "Designed and built a fully customized learning management system tailored to specific business needs with custom workflows, certification tracking, and branded learning paths",
    impact: "Delivered a purpose-built learning platform that aligns with organizational processes and goals",
    metrics: {
      primary: "100%",
      primaryLabel: "Workflow customization",
      secondary: "50%",
      secondaryLabel: "Training completion improvement",
    },
    technologies: ["Cloud Platform", "Custom Development", "API Integration", "Analytics Dashboard"],
    services: ["Enterprise Software", "Product Engineering", "Design Engineering"],
    image: "/images/productEngineering/product-engineering.jpg",
    slug: "custom-lms-platform",
    excerpt: "Custom learning management system built for unique business requirements",
  },
  {
    id: 6,
    featured: false,
    spotlight: false,
    clientType: "Educational Institution",
    industry: "Healthcare",
    challenge: "Student counselling cases managed through spreadsheets and paper files, making it difficult to track progress, maintain confidentiality, and generate insights",
    solution: "Developed a secure digital counselling management system with case tracking, progress monitoring, appointment scheduling, and confidential record keeping",
    impact: "Streamlined counselling operations with secure digital records and improved student support outcomes",
    metrics: {
      primary: "80%",
      primaryLabel: "Reduction in admin time",
      secondary: "100%",
      secondaryLabel: "Case tracking compliance",
    },
    technologies: ["Secure Cloud Platform", "Data Encryption", "Workflow Automation", "Analytics"],
    services: ["Product Engineering", "Enterprise Software", "Data Engineering"],
    image: "/images/qualityEngineering/quality-engineering.jpg",
    slug: "counselling-management-system",
    excerpt: "Secure digital case management for student counselling with progress tracking",
  },
  {
    id: 7,
    featured: false,
    spotlight: false,
    clientType: "Enterprise Organization",
    industry: "Enterprise",
    challenge: "Business knowledge scattered across documents and systems, with no efficient way to search, retrieve, or automate knowledge-based processes",
    solution: "Implemented Microsoft SharePoint-based knowledge management system with AI-powered search, automated document processing, and intelligent workflow automation",
    impact: "Centralized business knowledge with AI-driven discovery and automated information processing",
    metrics: {
      primary: "70%",
      primaryLabel: "Faster information retrieval",
      secondary: "60%",
      secondaryLabel: "Process automation achieved",
    },
    technologies: ["Microsoft SharePoint", "AI/ML", "Power Automate", "Azure Cognitive Services"],
    services: ["Enterprise Software", "AI Engineering", "Process Automation"],
    image: "/images/integrationEngineering/integration-engineering.jpg",
    slug: "sharepoint-knowledge-ai",
    excerpt: "AI-powered knowledge management on Microsoft SharePoint",
  },
  {
    id: 8,
    featured: false,
    spotlight: false,
    clientType: "Corporate Enterprise",
    industry: "Enterprise",
    challenge: "Inconsistent brand identity across employee communications, with no standardized email signatures or company-wide theming",
    solution: "Executed complete Microsoft enterprise transformation with centralized email signature management, company-wide branding themes, and unified communication standards",
    impact: "Achieved consistent brand identity across all employee communications and digital touchpoints",
    metrics: {
      primary: "100%",
      primaryLabel: "Brand consistency achieved",
      secondary: "1000+",
      secondaryLabel: "Employees standardized",
    },
    technologies: ["Microsoft 365", "Azure AD", "Exchange Online", "Power Platform"],
    services: ["Enterprise Software", "Integration Engineering", "Cloud Engineering"],
    image: "/images/cloudEngineering/cloud-engineering.jpg",
    slug: "microsoft-enterprise-transformation",
    excerpt: "Microsoft-powered enterprise communications with unified brand identity",
  },
  {
    id: 9,
    featured: false,
    spotlight: false,
    clientType: "Professional Services Firm",
    industry: "Enterprise",
    challenge: "No efficient way for employees to share professional profiles and for the company to maintain individual employee websites and digital business cards",
    solution: "Built a digital business card platform with employee website generator, enabling personalized professional profiles with company branding",
    impact: "Empowered employees with professional digital presence while maintaining brand consistency",
    metrics: {
      primary: "500+",
      primaryLabel: "Digital profiles created",
      secondary: "10x",
      secondaryLabel: "Faster profile sharing",
    },
    technologies: ["Web Platform", "CMS", "Cloud Hosting", "API Integration"],
    services: ["Product Engineering", "Design Engineering", "Cloud Engineering"],
    image: "/images/designEngineering/design-engineering.jpg",
    slug: "digital-business-cards",
    excerpt: "Digital business cards and employee websites for professional networking",
  },
  {
    id: 10,
    featured: false,
    spotlight: false,
    clientType: "Community Organization",
    industry: "Community",
    challenge: "Political groups, alumni associations, and professional communities struggling to manage memberships, communications, and engagement activities",
    solution: "Developed a comprehensive community management platform with membership tracking, event management, communication tools, and engagement analytics",
    impact: "Unified community management with streamlined membership operations and enhanced member engagement",
    metrics: {
      primary: "3x",
      primaryLabel: "Member engagement increase",
      secondary: "90%",
      secondaryLabel: "Admin workload reduction",
    },
    technologies: ["Web Platform", "Mobile App", "CRM Integration", "Analytics Dashboard"],
    services: ["Product Engineering", "Design Engineering", "Integration Engineering"],
    image: "/images/productEngineering/product-engineering.jpg",
    slug: "community-membership-platform",
    excerpt: "Community platform for associations, alumni networks, and professional groups",
  },
];

export const industryStories = [
  {
    industry: "Telecommunications",
    challenge: "Manual catalogue matching consuming hours of engineering time",
    outcome: "Minutes instead of hours with AI-powered catalogue automation",
  },
  {
    industry: "Transport",
    challenge: "Scattered EV charging operations and fleet inefficiencies",
    outcome: "Unified fleet management with real-time charging optimization",
  },
  {
    industry: "Financial Services",
    challenge: "Fragmented loyalty and payment experience affecting retention",
    outcome: "Integrated loyalty rewards and seamless payment in one app",
  },
  {
    industry: "Community",
    challenge: "Large families losing touch across generations and distances",
    outcome: "Connected platform for news, fundraising, and relationship discovery",
  },
  {
    industry: "Education",
    challenge: "Off-the-shelf LMS failing to meet unique business workflows",
    outcome: "Custom learning platform tailored to specific operational needs",
  },
  {
    industry: "Healthcare",
    challenge: "Student counselling cases tracked in spreadsheets and paper",
    outcome: "Digital case management with progress tracking and secure records",
  },
];

export const getFeaturedCaseStudies = () => {
  return caseStudies.filter((study) => study.featured);
};

export const getSpotlightCaseStudies = () => {
  return caseStudies.filter((study) => study.spotlight);
};

export const getCaseStudyBySlug = (slug) => {
  return caseStudies.find((study) => study.slug === slug);
};

export const getCaseStudiesByIndustry = (industry) => {
  return caseStudies.filter((study) => study.industry === industry);
};
