export const caseStudies = [
  {
    id: 1,
    featured: true,
    spotlight: true,
    clientType: "Leading Retail Chain",
    industry: "Retail",
    challenge: "Outdated checkout systems causing long queues and customer dissatisfaction during peak hours",
    solution: "Developed AI-powered self-checkout solution with computer vision and real-time inventory management",
    impact: "Reduced average checkout time by 40% and increased customer satisfaction scores by 35%",
    metrics: {
      primary: "40%",
      primaryLabel: "Reduction in checkout time",
      secondary: "35%",
      secondaryLabel: "Increase in customer satisfaction",
    },
    technologies: ["AI/ML", "Computer Vision", "Cloud Infrastructure", "Real-time Analytics"],
    services: ["AI Engineering", "Product Engineering", "Cloud Engineering"],
    image: "/images/productEngineering/product-engineering.jpg",
    slug: "retail-checkout-transformation",
    excerpt: "How we transformed the checkout experience for a major retail chain using AI-powered solutions",
  },
  {
    id: 2,
    featured: true,
    spotlight: true,
    clientType: "Financial Services Group",
    industry: "Financial Services",
    challenge: "Manual fraud detection processes unable to keep pace with increasing transaction volumes and sophisticated fraud patterns",
    solution: "Implemented machine learning-based fraud detection system with real-time risk scoring and automated alerting",
    impact: "Detected 300% more fraudulent transactions while reducing false positives by 60%",
    metrics: {
      primary: "300%",
      primaryLabel: "More fraud detected",
      secondary: "60%",
      secondaryLabel: "Reduction in false positives",
    },
    technologies: ["Machine Learning", "Real-time Processing", "Data Analytics", "API Integration"],
    services: ["AI Engineering", "Data Engineering", "Fintech Engineering"],
    image: "/images/fintechEngineering/fintech-engineering.jpg",
    slug: "fraud-detection-ai",
    excerpt: "Revolutionizing fraud detection for a leading financial institution with advanced ML algorithms",
  },
  {
    id: 3,
    featured: true,
    spotlight: true,
    clientType: "Insurance Provider",
    industry: "Insurance",
    challenge: "Claims processing taking 5-7 days with high manual intervention and inconsistent decision-making",
    solution: "Built intelligent claims automation platform using AI for document processing, risk assessment, and automated approvals",
    impact: "Reduced claims processing time from 5-7 days to under 24 hours with 95% accuracy",
    metrics: {
      primary: "24 hours",
      primaryLabel: "Average processing time",
      secondary: "95%",
      secondaryLabel: "Processing accuracy",
    },
    technologies: ["AI/ML", "Document Processing", "Workflow Automation", "Cloud Platform"],
    services: ["AI Engineering", "Process Automation", "Enterprise Software"],
    image: "/images/designEngineering/design-engineering.jpg",
    slug: "insurance-claims-automation",
    excerpt: "Streamlining insurance claims processing with intelligent automation and AI-powered decision-making",
  },
  {
    id: 4,
    featured: true,
    spotlight: false,
    clientType: "Transportation Authority",
    industry: "Transport",
    challenge: "Inefficient road asset management leading to increased maintenance costs and safety concerns",
    solution: "Developed comprehensive road asset management system with IoT sensors, predictive analytics, and real-time monitoring",
    impact: "Reduced maintenance costs by 25% and improved road safety metrics by 30%",
    metrics: {
      primary: "25%",
      primaryLabel: "Cost reduction",
      secondary: "30%",
      secondaryLabel: "Safety improvement",
    },
    technologies: ["IoT", "Data Analytics", "Predictive Modeling", "Cloud Infrastructure"],
    services: ["Data Engineering", "Cloud Engineering", "Integration Engineering"],
    image: "/images/dataEngineering/data-engineering.jpg",
    slug: "road-asset-management",
    excerpt: "Transforming highway infrastructure management with IoT and predictive analytics",
  },
  {
    id: 5,
    featured: false,
    spotlight: false,
    clientType: "Healthcare Technology Company",
    industry: "Healthcare",
    challenge: "Legacy systems unable to handle patient data analytics and personalized care recommendations at scale",
    solution: "Migrated to cloud-native architecture with advanced data analytics and AI-powered patient insights",
    impact: "Enabled personalized care for 78 million patients with 50% faster data processing",
    metrics: {
      primary: "78M",
      primaryLabel: "Patients served",
      secondary: "50%",
      secondaryLabel: "Faster processing",
    },
    technologies: ["Cloud Native", "Data Analytics", "AI/ML", "Microservices"],
    services: ["Cloud Engineering", "Data Engineering", "Product Engineering"],
    image: "/images/cloudEngineering/cloud-engineering.jpg",
    slug: "healthcare-cloud-migration",
    excerpt: "Enabling personalized healthcare at scale through cloud transformation and data intelligence",
  },
  {
    id: 6,
    featured: false,
    spotlight: false,
    clientType: "E-commerce Platform",
    industry: "Retail",
    challenge: "Supply chain disruptions causing inventory mismatches and delayed deliveries",
    solution: "Built AI-driven supply chain optimization platform with demand forecasting and automated inventory management",
    impact: "Reduced inventory costs by 20% and improved delivery accuracy to 98%",
    metrics: {
      primary: "20%",
      primaryLabel: "Inventory cost reduction",
      secondary: "98%",
      secondaryLabel: "Delivery accuracy",
    },
    technologies: ["AI/ML", "Supply Chain Analytics", "Cloud Platform", "API Integration"],
    services: ["AI Engineering", "Data Engineering", "Cloud Engineering"],
    image: "/images/productEngineering/product-engineering.jpg",
    slug: "supply-chain-optimization",
    excerpt: "Optimizing supply chain operations with AI-powered forecasting and inventory management",
  },
  {
    id: 7,
    featured: false,
    spotlight: false,
    clientType: "Banking Institution",
    industry: "Financial Services",
    challenge: "Customer onboarding process taking 3-5 days with high abandonment rates",
    solution: "Developed digital onboarding platform with identity verification, document processing, and automated KYC",
    impact: "Reduced onboarding time to under 15 minutes with 90% customer satisfaction",
    metrics: {
      primary: "15 min",
      primaryLabel: "Onboarding time",
      secondary: "90%",
      secondaryLabel: "Customer satisfaction",
    },
    technologies: ["AI/ML", "Document Processing", "Identity Verification", "Mobile Platform"],
    services: ["Fintech Engineering", "Product Engineering", "AI Engineering"],
    image: "/images/fintechEngineering/fintech-engineering.jpg",
    slug: "digital-onboarding",
    excerpt: "Transforming customer onboarding experience with digital-first solutions and AI automation",
  },
  {
    id: 8,
    featured: false,
    spotlight: false,
    clientType: "Manufacturing Company",
    industry: "Manufacturing",
    challenge: "Production line inefficiencies causing 15% waste and quality control issues",
    solution: "Implemented IoT-based quality control system with real-time monitoring and predictive maintenance",
    impact: "Reduced production waste by 30% and improved quality metrics by 25%",
    metrics: {
      primary: "30%",
      primaryLabel: "Waste reduction",
      secondary: "25%",
      secondaryLabel: "Quality improvement",
    },
    technologies: ["IoT", "Data Analytics", "Predictive Analytics", "Cloud Platform"],
    services: ["Data Engineering", "Cloud Engineering", "Integration Engineering"],
    image: "/images/dataEngineering/data-engineering.jpg",
    slug: "manufacturing-quality-control",
    excerpt: "Enhancing manufacturing efficiency with IoT sensors and predictive quality control",
  },
  {
    id: 9,
    featured: false,
    spotlight: false,
    clientType: "Telecommunications Provider",
    industry: "Telecommunications",
    challenge: "Network performance issues affecting customer experience and increasing support costs",
    solution: "Built network analytics platform with real-time monitoring, predictive maintenance, and automated optimization",
    impact: "Improved network uptime to 99.9% and reduced support tickets by 40%",
    metrics: {
      primary: "99.9%",
      primaryLabel: "Network uptime",
      secondary: "40%",
      secondaryLabel: "Support reduction",
    },
    technologies: ["Data Analytics", "Real-time Processing", "Cloud Infrastructure", "API Integration"],
    services: ["Data Engineering", "Cloud Engineering", "Integration Engineering"],
    image: "/images/cloudEngineering/cloud-engineering.jpg",
    slug: "network-analytics-platform",
    excerpt: "Optimizing network performance with advanced analytics and predictive maintenance",
  },
  {
    id: 10,
    featured: false,
    spotlight: false,
    clientType: "Energy Company",
    industry: "Energy",
    challenge: "Inefficient energy distribution causing high operational costs and customer complaints",
    solution: "Developed smart grid management system with AI-powered load balancing and demand forecasting",
    impact: "Reduced operational costs by 18% and improved customer satisfaction by 45%",
    metrics: {
      primary: "18%",
      primaryLabel: "Cost reduction",
      secondary: "45%",
      secondaryLabel: "Satisfaction increase",
    },
    technologies: ["AI/ML", "IoT", "Data Analytics", "Cloud Platform"],
    services: ["AI Engineering", "Data Engineering", "Cloud Engineering"],
    image: "/images/cloudEngineering/cloud-engineering.jpg",
    slug: "smart-grid-management",
    excerpt: "Modernizing energy distribution with AI-powered smart grid solutions",
  },
];

export const industryStories = [
  {
    industry: "Retail",
    challenge: "Checkout queues causing customer frustration",
    outcome: "40% reduction in checkout time with AI-powered self-service solutions",
    icon: "🛒",
  },
  {
    industry: "Financial Services",
    challenge: "Fraud detection lagging behind sophisticated attacks",
    outcome: "300% improvement in fraud detection with ML-powered real-time analysis",
    icon: "💳",
  },
  {
    industry: "Insurance",
    challenge: "Claims processing taking 5-7 days",
    outcome: "24-hour claims processing with 95% accuracy using intelligent automation",
    icon: "🛡️",
  },
  {
    industry: "Transport",
    challenge: "Road maintenance costs escalating",
    outcome: "25% cost reduction through predictive asset management and IoT monitoring",
    icon: "🚗",
  },
  {
    industry: "Healthcare",
    challenge: "Legacy systems limiting patient care personalization",
    outcome: "78M patients served with personalized care through cloud-native transformation",
    icon: "🏥",
  },
  {
    industry: "Manufacturing",
    challenge: "Production waste and quality control issues",
    outcome: "30% waste reduction with IoT-based quality control and predictive maintenance",
    icon: "🏭",
  },
];

export const getFeaturedCaseStudies = () => {
  return caseStudies.filter((study) => study.featured);
};

export const getSpotlightCaseStudies = () => {
  return caseStudies.filter((study) => study.spotlight);
};

export const getCaseStudyBySlug = (slug) => {
  return caseStudies.find((study) => study.slug === slug);
};

export const getCaseStudiesByIndustry = (industry) => {
  return caseStudies.filter((study) => study.industry === industry);
};

